config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

 

  get '/products/' =>  "products#index"
  get '/products/new' =>  "products#new"
  post '/products' => "products#create"
  get '/products/fruit' => "products#fruit"
  get '/products/vegetable' => "products#vegetable"
  get '/products/meat' => "products#meat"
  get '/products/dairy' => "products#dairy"
  get '/products/pantry' => "products#pantry"
  get '/products/search' => "products#search"
  post '/products/search' => "products#search"
  #get '/search', to: "products#search"
  #post '/search', to: "products#search"

  #Posting to array
  
  get '/products/myproduct' => "products#myproduct"
  
  #Send back product to client
  get '/products/:id' => "products#show", as: "product"
  get '/products' => "products#about"
  
  delete '/products/:id' => 'products#destroy'


  
  get '/farmers'  =>  "farmers#index"
  get '/farmers/new'  =>  "farmers#new"
  post '/farmers/new'  =>  "farmers#new"
  post '/farmers' =>  "farmers#create"
  get '/farmers/mypage' => "farmers#mypage"
  get '/farmers/:id' =>  "farmers#show", as: "farmer"
  


  resources :farmers do
    member do
      delete :delete_photo
    end
  end


  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :products
  resources :orders
  resources :line_items
  resources :type
  resources :farmers


end

app/views/shared/_footer.html.erb
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  
  <div class="text-center p-3 mt-5 " style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright: Farmers-Direct
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

<%= link_to'Farmers Direct', root_path, class:"navbar-brand" %>

  <!--Responsive sandwich icon, NOT WORKING! TO FIX TIME PERMITING -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navigation items -->
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <%= link_to'Products', root_path, class:"nav-item nav-link active" %>
    <%= link_to'Local-farmers', farmers_path, class:"nav-item nav-link active" %>

     <!-- All users can do these things if they NOT yet signed in -->
    <% if !user_signed_in? %> 
        <%= link_to'Sign-in', user_session_path, class:"nav-item nav-link active" %>
        <%= link_to'Sign-up', new_user_registration_path, class:"nav-item nav-link active" %>
    <% else %>
 <!-- If they are already signed in, only the signout displays -->
      <%=link_to 'Sign Out', destroy_user_session_path, method: 'delete', class:"nav-item 
        nav-link active" %>


        <!-- Shows only for admins and farmers -->
         <% if user_signed_in? and (current_user.admin? or current_user.farmer?) %>

          <%= link_to'New Product', products_new_path, class:"nav-item nav-link active" %>
          <%= link_to'My Products', products_myproduct_path, class:"nav-item nav-link active" %>
          <%= link_to'My Page', farmers_mypage_path, class:"nav-item nav-link active" %>
         
          
        <%end%>
    <%end%>


<!-- Search bar, any user can see and use  -->
  <%= form_tag(products_search_path, :method => "get") do %>
<div class="input-group rounded">
<%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control rounded"  %>
 <%= button_tag "Product search", :class=> 'btn btn-secondary', :name => nil%>

</div>
<% end %>

<!-- Only displays if the user is signed in. Any user group.  -->
<% if user_signed_in? %>
 <%= link_to cart_path(@current_cart), class:"nav-item nav-link active" do %>
            <i class="bi bi-cart3" style="font-size: 1.25rem;" ></i>
            <% end %>
<% end %>

    </div>
  </div>
</nav>

app/views/shared/_product_nav.html.erb
<!-- Navbar for looking through products by category  -->

<div class="container">
<nav class="navbar sticky-top">
<%= link_to "Fruits", products_fruit_path, class: "navbar-brand" %>
<%= link_to "Vegetables", products_vegetable_path, class: "navbar-brand" %>
<%= link_to "Meat", products_meat_path, class: "navbar-brand" %>
<%= link_to "Dairy", products_dairy_path, class: "navbar-brand" %>
<%= link_to "Pantry", products_pantry_path, class: "navbar-brand" %>
</nav>
</div>