config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

 

  get '/products/' =>  "products#index"
  get '/products/new' =>  "products#new"
  post '/products' => "products#create"
  get '/products/fruit' => "products#fruit"
  get '/products/vegetable' => "products#vegetable"
  get '/products/meat' => "products#meat"
  get '/products/dairy' => "products#dairy"
  get '/products/pantry' => "products#pantry"
  get '/products/search' => "products#search"
  post '/products/search' => "products#search"
  #get '/search', to: "products#search"
  #post '/search', to: "products#search"

  #Posting to array
  
  get '/products/myproduct' => "products#myproduct"
  
  #Send back product to client
  get '/products/:id' => "products#show", as: "product"
  get '/products' => "products#about"
  
  delete '/products/:id' => 'products#destroy'


  
  get '/farmers'  =>  "farmers#index"
  get '/farmers/new'  =>  "farmers#new"
  post '/farmers/new'  =>  "farmers#new"
  post '/farmers' =>  "farmers#create"
  get '/farmers/mypage' => "farmers#mypage"
  get '/farmers/:id' =>  "farmers#show", as: "farmer"
  


  resources :farmers do
    member do
      delete :delete_photo
    end
  end


  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :products
  resources :orders
  resources :line_items
  resources :type
  resources :farmers


end

app/models/farmer.rb
class Farmer < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  #original code
  # validates :user_id, :uniqueness => { :scope => :user_id, 
  #   :message => "already exists" }

#shortened code

    validates :user_id, uniqueness: true
    
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController

    before_action :params_find, only: [:show, :update, :edit ]
    before_action :farmer_params, only: [:create ]
    before_action :isFarmer, only: [:new, :create, :edit, :update, :mypage]
    
    # Required to allow farmer to upload multiple images. 
    require "mini_magick"

    def index
        #@farmers = Farmer.all.order("farmer.name").eager_load(:name) - Attempt at Eagerloading, not taught in class and not great great resources easy to find :(
        @farmers = Farmer.all
        
    end

    def new
        @farmer = Farmer.new  
    end


    def edit
    end

    def show
    end


    def create
        @farmers = Farmer.create(farmer_params)
            if @farmers.save 
                #If the farmer can save thier new farm page, it will do so. 
                redirect_to farmers_path

            else 
                #If they are unable to create a farmer page, it will let them know. This is controlled in the model through a validates uniqueness to prevent farmer creating more than one page. 
                redirect_to root_path, notice: "You already have a farmer page, please edit your existing page. If you feel this is an error, please contact support."
            end
    end

    #allows farmer to update thier about them page. 
    def update
        @farmers.update(farmer_params)
        redirect_to @farmers, notice: "Details updated"
    end

    def params_find
        @farmers = Farmer.find(params[:id])
    end

    def farmer_params
        params.require(:farmer).permit(:name, :about, :abn, :user_id, photos: [] ) 
        #Regular params, photo is an array and support mulitple picture uploads and assigned to that farmer. 
    end

    #ability to delete photo (I think this is removed from views currently, to be re-added, not commenting out as required for future dev)
    def delete_photo
        photo = ActiveStorage::Attachment.find(params[:id])
        photo.purge
        redirect_back(fallback_location: farmers_path)
      end

      def mypage
        @farmers = Farmer.all
      end

    private 

    # Prevents user accessing pages if they are not a farmer, e.g if they had a page saved or followed a link and they were not logged in or only logged in as a general user. 
    def isFarmer
        begin
            if user_signed_in? and !current_user.farmer?
                # if user_signed_in? and (!current_user.farmer or !current_user.admin) - This should be the correct permission, however prevents farmer accessing elements. Add to bug fixes for future dev.
                redirect_to products_path, alert: "You must be a registered farmer to access these pages"
            else
            if !user_signed_in?
                redirect_to products_path, alert: "Please login as a farmer to access this page"
            end
        end
        
        rescue StandardError => e
            puts e.message
            redirect_to products_path, alert: "Please login as a farmer to view"
        end
    end
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/views/farmers/details.html.erb
<H1> Please complete your page </H1>

<%= form_with model: @farmer do |form| %>

<%= form.label :business_name %>
<%= form.text_field :name %>

<%= form.label :about %>
<%= form.text_field :description  %>

<%= form.label :abn %>
<%= form.text_field :abn

<%= form.label :stock %>
<%= form.number_field :stock %>

<%= form.hidden_field :user_id, value: current_user.id%>



<%= form.submit "submit" %>

<%end%>

app/views/farmers/edit.html.erb
<br/>
<div class="d-flex justify-content-center">
  <H1> Edit your farm</H1>
</div>

<div class="d-flex justify-content-center">

  <%= form_for (@farmers) do |form| %>
    <div class="mt-4 form-group">
      <%= form.label :farm_name %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="mt-4 form-group">
      <%= form.label :about_your_farm %>
      <%= form.text_field :about, class: "form-control", required: true  %>
    </div>

    <div class="mt-4 form-group">
      <%= form.label :ABN %>
      <%= form.text_field :abn, class: "form-control", required: true%>
    </div>


    <div class="mt-4 form-group">
      <%= form.label :photo %>
      <%= form.file_field :photos, accept: "image/jpg, image/png, image/jpeg ", class: "form-control", multiple: "true", required: true%>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id%>

    <br/>
    
    <%= form.submit "submit", class: "btn btn-secondary" %>

  <% end %>
</div>

app/views/farmers/index.html.erb
<!-- Displays all farmers with option for user to select into the farmers page to learn more about them -->

<h1> Our Farmers </h1>

<div class="container">
  <div class="row row-cols-1 row-cols-md-3">
    <% @farmers.each do |farmer| %>
        <div class="col-md-4 mt-5">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title"> <%=link_to farmer.name, farmer_path(farmer.id) %></h5>
              <p class="card-text"><%=farmer.about%></p>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/farmers/mypage.html.erb
<!-- Iterates through all the farmers with the condition that the informatio displayed belongs to that farmer, this page allows the farmer to have a clear view of the details they are displaying to end users and make edits to this, They cannot however delete thier page at present, to be added as future dev. -->
<% @farmers.each do |farmer| %>
  <% if user_signed_in? and (current_user.admin? or current_user.id==farmer.user_id) %>


  <div class="container mt-5 mb-5">
    <div class="row">

      <div class="col">
        <h1><%=farmer.name%></h1>
      </div>

      <div class="col">
        <p><%=farmer.about%></p>
      </div>

    </div>
  </div>

  <%= link_to "Edit", edit_farmer_path(farmer) %>

  <br/>

  <!-- Displays all farmers images in a carosole, design not great, requires better design -->
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% if farmer.photos.any? %>
        <% farmer.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= index == 0 ? 'active' : ''  %>">
              <%= image_tag photo, alt: "website logo", class: "bd-placeholder-img card-img-top pb-5", width: "100%", height:"450" %>
            </div>
        <%end%>
      <%end%>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>

    <button class="carousel-control-next" type="button" 
    data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    
  </div>
          
  <% end %>
<% end %>
 

app/views/farmers/new.html.erb
<br/>

<div class="d-flex justify-content-center">
  <H1> About your farm</H1>
</div>

<div class="d-flex justify-content-center">
  <%= form_for (@farmer) do |form| %>

    <div class="mt-4 form-group">
      <%= form.label :farm_name %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="mt-4 form-group">
      <%= form.label :about_your_farm %>
      <%= form.text_field :about, class: "form-control", required: true  %>
    </div>

    <div class="mt-4 form-group">
      <%= form.label :ABN %>
      <%= form.text_field :abn, class: "form-control", required: true%>
    </div>

    <div class="mt-4 form-group">
      <%= form.label :photo %>
      <%= form.file_field :photos, accept: "image/jpg, image/png, image/jpeg ", class: "form-control", multiple: "true", required: true %>
    </div>


<!-- pulls user id into database to connect the farmer page to that user -->
    <%= form.hidden_field :user_id, value: current_user.id %>

    <br/>

    <%= form.submit "submit", class: "btn btn-secondary" %>

  <% end %>
</div>

app/views/farmers/show.html.erb
<!-- displays one farmers details after selecting into that farmer page -->
<div class="container mt-5 mb-5">
  <div class="row">

    <div class="col">
      <h1><%=@farmers.name%></h1>
    </div>

    <div class="col">
      <p><%=@farmers.about%></p>
    </div>

  </div>
</div>

<br/>

<!-- Displays all farmers images in a carosole, design not great, requires better design -->
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% if @farmers.photos.any? %>
      <% @farmers.photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= index == 0 ? 'active' : ''  %>">
            <%= image_tag photo, alt: "website logo", class: "bd-placeholder-img card-img-top pb-5", width: "100%", height:"450" %>
          </div>
      <%end%>
    <%end%>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>

  <button class="carousel-control-next" type="button" 
  data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  
</div>
         
         