config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

 

  get '/products/' =>  "products#index"
  get '/products/new' =>  "products#new"
  post '/products' => "products#create"
  get '/products/fruit' => "products#fruit"
  get '/products/vegetable' => "products#vegetable"
  get '/products/meat' => "products#meat"
  get '/products/dairy' => "products#dairy"
  get '/products/pantry' => "products#pantry"
  get '/products/search' => "products#search"
  post '/products/search' => "products#search"
  #get '/search', to: "products#search"
  #post '/search', to: "products#search"

  #Posting to array
  
  get '/products/myproduct' => "products#myproduct"
  
  #Send back product to client
  get '/products/:id' => "products#show", as: "product"
  get '/products' => "products#about"
  
  delete '/products/:id' => 'products#destroy'


  
  get '/farmers'  =>  "farmers#index"
  get '/farmers/new'  =>  "farmers#new"
  post '/farmers/new'  =>  "farmers#new"
  post '/farmers' =>  "farmers#create"
  get '/farmers/mypage' => "farmers#mypage"
  get '/farmers/:id' =>  "farmers#show", as: "farmer"
  


  resources :farmers do
    member do
      delete :delete_photo
    end
  end


  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :products
  resources :orders
  resources :line_items
  resources :type
  resources :farmers


end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  has_many :orders

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user! , only: [:new, :create]

  def show
    @cart = @current_cart
  end

  #Empty's the cart of all items
  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
        </div>

        <!-- Iterates through all the cart items and adds thier attributes through an instance variable-->
        <% @cart.line_items.each do |line_item| %>
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">

                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2"><%= line_item.product.name %></p>
                </div>
                
                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <!-- Ensures that the user cannot go under 0 in quanity by removing display of minus button-->
                  <% if line_item.quantity >= 1 %>
                    <!-- Add one to quantity, functionality outlined in controller-->
                    <%= link_to " - ", line_item_reduce_path(:id => line_item), method: :post %>  
                  <%end%>

                    <h5 class="text-grey mt-1 mr-1 ml-1"><%= line_item.quantity %></h5><i class="fa fa-plus text-success"></i>
                    <!-- Reduces one to quantity, functionality outlined in controller-->
                    <%= link_to " + ", line_item_add_path(:id => line_item), method: :post %>
                </div>


                  <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                    <h5 class="mb-0">Price per item: <%= number_to_currency(line_item.product.price)%></h5>
                  </div>

                  <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                    <%= link_to "X", line_item_path(:id => line_item), method: :delete %><i class="fa fa-trash mb-1 text-danger"></i>
                    <i class="fas fa-trash fa-lg"></i></a>
                  </div>

              </div>
            </div>
          </div>  
        <%end%>

        <h3>Sub total: <%= number_to_currency(@current_cart.price) %></h3>
        <p> Please note the minimum spend order is $30</p>
        <%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>

        <br/>
        
          <!-- Prevents user checking out unless they have spent the minimum order amount-->
          <% if @current_cart.price >= 30 %>
            <button class="btn btn-outline-dark mt-3" type="button">
            <%= link_to "Proceed to checkout", new_order_path %></button></div>
          <% end %>
          </div>
        </div>
      </div>
    </div> 
  </div>
</section>