config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

 

  get '/products/' =>  "products#index"
  get '/products/new' =>  "products#new"
  post '/products' => "products#create"
  get '/products/fruit' => "products#fruit"
  get '/products/vegetable' => "products#vegetable"
  get '/products/meat' => "products#meat"
  get '/products/dairy' => "products#dairy"
  get '/products/pantry' => "products#pantry"
  get '/products/search' => "products#search"
  post '/products/search' => "products#search"
  #get '/search', to: "products#search"
  #post '/search', to: "products#search"

  #Posting to array
  
  get '/products/myproduct' => "products#myproduct"
  
  #Send back product to client
  get '/products/:id' => "products#show", as: "product"
  get '/products' => "products#about"
  
  delete '/products/:id' => 'products#destroy'


  
  get '/farmers'  =>  "farmers#index"
  get '/farmers/new'  =>  "farmers#new"
  post '/farmers/new'  =>  "farmers#new"
  post '/farmers' =>  "farmers#create"
  get '/farmers/mypage' => "farmers#mypage"
  get '/farmers/:id' =>  "farmers#show", as: "farmer"
  


  resources :farmers do
    member do
      delete :delete_photo
    end
  end


  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  resources :products
  resources :orders
  resources :line_items
  resources :type
  resources :farmers


end

app/models/product.rb
class Product < ApplicationRecord
 belongs_to :user
 has_one_attached :productpic
 has_many :line_items, dependent: :destroy 
 #has_many :user, through :orders
 
def self.search(search)
    where("lower(product.name) LIKE :search", search: "%#{search.downcase}%".uniq)
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user! , only: [:new, :create]
    before_action :params_find, only: [:show, :edit, :update, :destroy]
    before_action :isFarmer, only: [:new, :create, :edit, :update, :destroy, :myproduct]
    before_action :check_ownership, only: [:edit, :update, :destroy]
    


    #Main product page, provides view of all products through instance variable. 
    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    #def show - not required, not enough details on products. To remove description from model, serves no purpose if no show page. 


    #Controls the creation of new products and handles errors if unable to create the product. 
    def create
        begin
            @product = Product.create(product_params)
            redirect_to products_path, notice: "Your product #{@product.name} is up for sale!"
        rescue StandardError => e
            puts e.message
            redirect_to products_path, notice: "There has been an error, your product wasn't created. Please try again or contact support"
        end
    end

    
    # Allows farmers and admins to delete products
    def destroy     
        @product.destroy
        redirect_to root_path, notice: "#{@product.name} was removed from product range"
    end

    #Updates product by searching from product ID first (before_action), then using update method
    def edit
    end

    #Creates an instance variable so only items with set category is displayed in iteration. 
    def fruit
        @fruits = Product.where(category: "Fruit")
    end

    def vegetable
        @veggies = Product.where(category: "Vegetable")
    end

    def meat
        @meats = Product.where(category: "Meat")
    end

    def dairy
        @dairys = Product.where(category: "Dairy")
    end

    def pantry
        @pantrys = Product.where(category: "Pantry")
    end


    #Allows farmer to see own products. Products displayed is then controlled in the view to say only products belonging to that user to display. 
    def myproduct
        @products = Product.all
    end

    #Updates product by searching from product ID first
    def update
        @product.update(product_params) 
        redirect_to products_path, notice: "#{@product.name} updated" 
    end

    #Search feature 
    def search 
 
        if params[:search].nil? #this is not currently finctioning correctly. Added to bug fix.
           redirect_to products_path, alert: "No products match your search" and return
        else
            @parameter = params[:search].downcase #Prevents issues with capital titles of titles 
        @products = Product.all.where("lower(name) LIKE :search", search: "%#{@parameter}%") #searches the product paramaters and matches attributes. E.g can search by name but also price. 
        end
    end


    private 
#Defines what params belong to a product and what can be passed through the relavant forms and connect to that object. 
    def product_params
        params.require(:product).permit(:name, :description, :price, :productpic, :category, :user_id)
    end
   
#Used for a before aciton on multiple crud operations, finds the params of prodcuts and creates an instance variable. 
    def params_find
        @product = Product.find(params[:id])
    end
 
    # Prevents user accessing pages if they are not a farmer, e.g if they had a page saved or followed a link and they were not logged in or only logged in as a general user. 
    def isFarmer
        begin
        if user_signed_in? and !current_user.farmer
           # if user_signed_in? and (!current_user.farmer or !current_user.admin) - This should be the correct permission, however prevents farmer accessing elements. Add to bug fixes for future dev.
            redirect_to products_path, alert: "You must be a registered farmer to access these pages"
        else
        if !user_signed_in?
            redirect_to products_path, alert: "Please login as a farmer to access this page"
        end
    end
    # If all else fails redirects the user to the products page and displays message
        rescue StandardError => e
            puts e.message
            redirect_to products_path, alert: "Please login as a farmer to view"
        end
    end

    # This is a two prong approach, potentially redundand do the the way the site permissions have been set in index. Purpose is to prevent user deleting other peoples products; however this is handled in views. 
    def check_ownership
        if !user_signed_in? and (!current_user.admin? or !current_user.id==@product.user_id) 
        redirect_to products_path, alert: "check ownership"
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/dairy.html.erb
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-2">
            <h1 class="masthead-heading mb-0">Dairy</h1>
        </div>
    </div>
</header>

<!-- Displays products only from one category -->
<%= render'shared/product_nav' %>

<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">

    <!-- Displays products only from one category -->
    <% @dairys.each do |product| %>

        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- show's nothing-->

        <%else%>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-150">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                    <p>$<%=product.price %></p>
                                </div>
                            </div>

                            <!-- Product actions-->
                            <div class="text-center">
                                <%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                            <% end %>
        <% end %>
</section>

app/views/products/edit.html.erb
<div class="d-flex justify-content-center">
    <%= form_for(@product) do |f| %>
    <div class="mt-4 form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true  %>
    </div>
    <div class="mt-4 form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control", required: true   %>
    </div>
    <div class="mt-4 form-group">
        <%= f.label :price %>
        <%= f.number_field :price, :step => "0.05", class: "form-control", required: true  %>
    </div>
    <div class="mt-4 form-group">
        <%= f.label :image %>
        <%= f.file_field :productpic, accept: "image/jpg, image/png, image/jpeg ", class: "form-control", required: true %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id%>
    <div class="mt-4 form-group">
        <%= f.submit "submit" %>
    </div>

    <%end%>
</div>

app/views/products/fruit.html.erb
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-2">
            <h1 class="masthead-heading mb-0">Fruit</h1>
        </div>
    </div>
</header>

<!-- Displays products only from one category -->
<%= render'shared/product_nav' %>

<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">

  <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% @fruits.each do |product| %>
        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- show's nothing-->

        <%else%>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-150">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                    <p>$<%=product.price %></p>
                                </div>
                            </div>

                            <!-- Product actions-->
                            <div class="text-center">
                                <%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                            <% end %>
        <% end %>
</section>

app/views/products/index.html.erb
                
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">Gold Coast</h1>
                    <h1 class="masthead-heading mb-0">Farmers Direct</h1>
                    <h3 class="masthead-subheading mb-0">Supporting our local Farmers</h3>
                </div>
            </div>

             <!-- Header-->
        </header>
            <br>
         <% if user_signed_in? and (current_user.admin? or current_user.farmer) %>
            <div class="container">
                <div class="row">
                    <div class="col-sm d-flex justify-content-center">
                   <%=link_to(image_tag("Button-hack-1.png"), farmers_new_path) %>
                    </div>
                    <div class="col-sm d-flex justify-content-center">
                    <%=link_to(image_tag("Button-hack-2.png"), products_new_path) %>
                    </div>
                    <div class="col-sm d-flex justify-content-center">
                    <%=link_to(image_tag("Button-hack-3.png"), products_myproduct_path) %>
                    
                    </div>
                </div>
                </div>
<%end%>
  
 <%= render'shared/product_nav' %>

        <!-- Section-->


  
  <section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">




  <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% @products.each do |product| %>
           <% if user_signed_in? and current_user.id==product.user_id %>
            <%else%>
             <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card shadow-sm">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>
                            <!-- Product details-->
                            <div class="card-body justify-content-center p-4">
                                <div class="text-center h-100">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                   <p>$<%=product.price %></p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <!-- Restrict permissions so a farmer cannot purchase his own products, but can purcahse other famrers products -->
                             
                            
                             <div class="text-center"><%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            <br />
                        

                                    <% if user_signed_in? and current_user.admin? %>
                                    <div class="text-center">
                                        <p><%= link_to "Edit", edit_product_path(product), class: "font-weight-light" %> |
                                        <%= link_to "Delete", product_path(product), class: "font-weight-light", method: :delete, data: {confirm: "Are you sure?"} %></p>
                                        </div>
                                    <% end %>
                
                                    </div>
                            </div>
                        </div>
                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
             <%end%>
        </section>
    </div>
         
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

app/views/products/meat.html.erb
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-2">
            <h1 class="masthead-heading mb-0">Meat</h1>
        </div>
    </div>
</header>

<!-- Displays products only from one category -->
<%= render'shared/product_nav' %>

<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">

  <!-- Displays products only from one category -->
        <% @meats.each do |product| %>
        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- show's nothing-->

        <%else%>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-150">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                    <p>$<%=product.price %></p>
                                </div>
                            </div>

                            <!-- Product actions-->
                            <div class="text-center">
                                <%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                            <% end %>
        <% end %>
</section>

app/views/products/myproduct.html.erb
      <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-2">
                    <h1 class="masthead-heading mb-0">Your Products</h1>
                </div>
            </div>

             <!-- Header-->
        </header>

<!-- Iterates through all the products with the condition that the products displayed belong to that farmer, this page allows the farmer to have a clear view of the current prodcuts for sale so they can make edits and remove products -->
<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">
        <% @products.each do |product| %>
        <% if user_signed_in? and (current_user.admin? or current_user.id==product.user_id) %>
       
              <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-100">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                   <p>$<%=product.price %></p>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="text-center">
                                <p><%= link_to "Edit", edit_product_path(product) %> |
                                <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %></p> 
                                    </div>
                            </div>
                        </div>
                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
             <% end %>
        </section>
    </div>

app/views/products/new.html.erb
<br />
<div class="d-flex justify-content-center">
<H1> Add a new product </H1>
</div>
<div class="d-flex justify-content-center">
<%= form_with model: @product do |f| %>
 <div class="mt-4 form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
</div>

<div class="mt-4 form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", required: true%>
</div>

<div class="mt-4 form-group">
<%= f.label :price %>
<%= f.number_field :price, :step => "0.05", class: "form-control", required: true%>
</div>

<div class="mt-4 form-group">
<%= f.label :image %>
<%= f.file_field :productpic, accept: "image/jpg, image/png, image/jpeg ", class: "form-control", required: true %>
</div>

<div class="mt-4 "dropdown-menu"">
<%= f.label :category %>
<%= f.select :category, [['Fruit','Fruit'],['Vegetable','Vegetable'],['Meat','Meat'],['Dairy','Dairy'],['Pantry','Pantry']],class: "dropdown-item", required: true %>
</div>

<!-- pulls user id into database to connect the product to that user -->
<%= f.hidden_field :user_id, value: current_user.id%>


<div class="mt-4 form-group">
<%= f.submit "submit", class: "btn btn-secondary" %>
</div>
<%end%>
</div>

app/views/products/pantry.html.erb
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-2">
            <h1 class="masthead-heading mb-0">Pantry</h1>
        </div>
    </div>
</header>

<!-- Displays products only from one category -->
<%= render'shared/product_nav' %>

<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">

<!-- Displays products only from one category -->
        <% @pantrys.each do |product| %>
        
        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- show's nothing-->

        <%else%>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-150">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                    <p>$<%=product.price %></p>
                                </div>
                            </div>

                            <!-- Product actions-->
                            <div class="text-center">
                                <%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                            <% end %>
        <% end %>
</section>

app/views/products/search.html.erb
<h1> Search Results <h1>
  <section class="row card-row-cols-1 row-cols-md-3">
        <% @products.each do |product| %>
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
            <%else%>
       
             <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-100">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                   <p>$<%=product.price %></p>
                                </div>
                            </div>
                        
                            <div class="text-center"><%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto" %>

                                <% if user_signed_in? and current_user.admin? %>
                                    <div class="text-center">
                                        <p><%= link_to "Edit", edit_product_path(product), class: "font-weight-light" %> |
                                        <%= link_to "Delete", product_path(product), class: "font-weight-light", method: :delete, data: {confirm: "Are you sure?"} %></p>
                                    </div>
                                <% end %>
                            
                                </div>
                            </div>
                        </div>
                    </div>
                        </div>
                    </div>
                      <% end %>
             <% end %>
                </div>
            </div>
          

app/views/products/vegetable.html.erb
<!-- Header-->
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-2">
            <h1 class="masthead-heading mb-0">Veggies</h1>
        </div>
    </div>
</header>

<!-- Displays products only from one category -->
<%= render'shared/product_nav' %>

<section class="row row-cols-1 row-cols-md-4 d-flex align-self-stretch">

  <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% @veggies.each do |product| %>
        <!-- Prevents a farmer viewing thier own product as a purchaser, farmer can go to thier products page to view thier current products and edit-->
        <% if user_signed_in? and current_user.id==product.user_id %>
        <!-- show's nothing-->

        <%else%>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="justify-content-center">
                    <div class="col-mb-4">
                        <div class="card h-150">
                            <!-- Product image-->
                            <%= image_tag product.productpic.representation(resize_to_limit: [190, 160]).processed, :crop => :fill if product.productpic.attached? %>

                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <!-- Product price-->
                                    <p>$<%=product.price %></p>
                                </div>
                            </div>

                            <!-- Product actions-->
                            <div class="text-center">
                                <%= button_to "Add to cart", line_items_path(:product_id => product.id), :class => "btn btn-outline-dark mt-auto mb-4" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                            <% end %>
        <% end %>
</section>